// flags: -Wall -Warray-parameter=2 -Wvla-parameter
void f1 (int[1]);
void f1 (int[2]);
void f2 (int[]);
void f2 (int[3]);
void f3 (int*);
void f3 (int[4]);
void f4 (int[*]);
void f4 (int[5]);
void f5 (int n, int[n]);
void f5 (int n, int[]);
void f6 (int n, int[n]);
void f6 (int n, int[n + 1]);
void f7 (int, int[*]);
void f7 (int n, int a[n]);
void f8 (int[2][3]);
void f8 (int[2][4]);
void f9 (int[static 2]);
void f9 (int[3]);
void f10 (int a[1]);
void f10 (int a[2]) { }
void g1 (int[1]);
void g1 (int[2]);
void g1 (int[3]);
void g2 (int[2]);
void g2 (int[]);
void g2 (int[3]);
void g3 (int (*)[2]);
void g3 (int (*)[3]);
void g4 (int n, int (*)[n]);
void g4 (int n, int (*)[2]);
typedef int A2[2];
void g5 (A2);
void g5 (int[3]);
void g6 (int *);
void g6 (int *);
void g6 (int[2]);
void g7 (int[2][3]);
void g7 (int(*)[3]);
void g8 (int a[restrict 2]);
void g8 (int a[restrict 3]);
void g9 (int n, int a[n]);
void g9 (int n, int a[n]);
void g10 (int n, int m, int a[n][m]);
void g10 (int n, int m, int a[m][n]);
void g11 (int n, int m, int a[n][m]);
void g11 (int n, int m, int a[*][*]);
void g12 (int n, int m, int a[n][m]);
void g12 (int n, int m, int a[3][m]);
void h1 (int *);
void h1 (int[2]);
void h1 (int[3]);
void h2 (int[2]);
void h2 (int *);
void h2 (int[3]);
void h3 (int[]);
void h3 (int[1]);
void h4 (int[1]);
void h4 (int[]);
void h5 (int[0]);
void h5 (int[2]);
void h6 (int[2]);
void h6 (int[2]) {}
void h7 (int[2]);
void h7 (int a[3]) {}
void h8 (int[static 2]);
void h8 (int[static 3]);
void h9 (int[const 2]);
void h9 (int[2]);
void h10 (int[*]);
void h10 (int[]);
void h11 (int, int[*]);
void h11 (int n, int[n]);
void h11 (int n, int[n]);
void h12 (int n, int[n]);
void h12 (int n, int[n]);
void h12 (int, int[*]);
void h13 (int (*)[]);
void h13 (int (*)[2]);
void h14 (int[][2]);
void h14 (int[3][2]);
void h15 (void *[2]);
void h15 (void *[3]);
void h16 (int (*)(void));
void h16 (int[2]);
