typedef struct Type { int i; } Type;
typedef int T;
int var;
void fv_ ();
void fvi (int);
void fvv (void);
void fvi_vp (Type, void*);
void fpv (void*);
void *a0 (int) __attribute__((malloc(0)));
void *a1 (int) __attribute__((malloc("")));
void *a2 (int) __attribute__((malloc(var)));
void *a3 (int) __attribute__((malloc(unknown)));
void *a4 (int) __attribute__((malloc(fv_)));
void *a5 (int) __attribute__((malloc(fvi)));
void *a6 (int) __attribute__((malloc(fvv)));
void *a7 (int) __attribute__((malloc(fvi_vp)));
void *a8 (int) __attribute__((malloc(fpv)));
void *a9 (int) __attribute__((malloc(T)));
int x = T;
