// flags: -std=c11 -pedantic-errors
_Static_assert(__builtin_expect(1,1), "a");
_Static_assert(__builtin_strlen("a") == 1, "b");
_Static_assert(__builtin_strlen("a"), "b");
_Static_assert(__builtin_popcount(3) == 2, "c");
_Static_assert(__builtin_popcountl(7) == 3, "c");
_Static_assert(__builtin_popcountll(-1) == 64, "c");
_Static_assert(__builtin_clz(1) == 31, "c");
_Static_assert(__builtin_clzl(1) == 63, "c");
_Static_assert(__builtin_ctz(8) == 3, "c");
_Static_assert(__builtin_ctzll(1ull << 40) == 40, "c");
_Static_assert(__builtin_ffs(8) == 4, "c");
_Static_assert(__builtin_ffs(0) == 0, "c");
_Static_assert(__builtin_parity(7) == 1, "c");
_Static_assert(__builtin_parityll(3) == 0, "c");
_Static_assert(__builtin_clrsb(1) == 30, "c");
_Static_assert(__builtin_clrsb(-1) == 31, "c");
_Static_assert(__builtin_clrsbll(0) == 63, "c");
_Static_assert(__builtin_constant_p(1), "c");
_Static_assert(__builtin_bswap16(0x1234) == 0x3412, "c");
_Static_assert(__builtin_bswap32(1) == 0x1000000, "c");
_Static_assert(__builtin_bswap64(1) == 0x100000000000000ull, "c");
_Static_assert(__builtin_abs(-5) == 5, "c");
_Static_assert(__builtin_llabs(-5) == 5, "c");
_Static_assert(__builtin_choose_expr(__builtin_popcount(3) == 2, 1, 0), "c");
enum { E1 = __builtin_popcount(5), E2 = __builtin_strlen("ab"), E3 = __builtin_expect(2,2), E4 = __builtin_clz(1) };
int arr1[__builtin_popcount(7)];
int arr2[__builtin_strlen("abc")];
int arr3[__builtin_expect(3,1)];
int arr4[__builtin_ctz(4)];
static int s1 = __builtin_popcount(15);
static int s2 = __builtin_strlen("abcd");
static long s3 = __builtin_expect(4,1);
static int s4 = __builtin_bswap32(1);
static int s5 = __builtin_clrsb(1);
static int s6 = __builtin_parity(7);
_Static_assert(__builtin_clz(0) == 32, "clz0");
_Static_assert(__builtin_ctz(0) == 32, "ctz0");
_Static_assert(__builtin_clzl(0) == 64, "clzl0");
_Static_assert(__builtin_ctzll(0) == 64, "ctzll0");
