// flags: -std=gnu11
struct S { int a; union { int b; int c; }; } __attribute__((designated_init));
struct S s2 = { 0, 0 };
struct S s3 = { .a = 5, 0 };
struct S s4 = { .a = 5, { 0 } };
struct T { int a; struct { int b; int c; } in; } __attribute__((designated_init));
struct T t1 = { 0, 1, 2 };
struct T t2 = { .a = 0, 1, 2 };
struct U { int a; struct T t; };
struct U u1 = { 1, 2, 3, 4 };
struct D { int a; struct { int b; int c; } in; int d[2]; } __attribute__((designated_init));
struct D d1 = { 1, { 2, 3 }, { 4, 5 } };
struct D d2 = { .a = 1, 2, 3, 4, 5 };
struct D da[2] = { { 1, 2, 3, 4, 5 }, 1, 2, 3, 4, 5 };
struct W { int w; struct D dd; };
struct W w1 = { 0, 1, 2, 3, 4, 5, 6 };
struct W w2 = { 0, { 1, 2, 3, 4, 5, 6 } };
struct E { struct D e; int f; } __attribute__((designated_init));
struct E e1 = { 1, 2, 3, 4, 5, 6 };
struct D d3 = { 1, 2, 3, 4, 5 };
struct F { int a; int d[2]; int e; } __attribute__((designated_init));
struct F f1 = { 1, 2, 3, 4 };
struct F f2 = { .a = 1, 2, 3, 4 };
struct G { int a; struct { int b; } in; int e; } __attribute__((designated_init));
struct G g1 = { 1, 2, 3 };
struct G g3 = { .in = 1, 3 };
struct H { int a; int b; int c; } __attribute__((designated_init));
struct H h1 = { 1, 2, 3 };
struct H h3 = { .c = 1, .a = 2 };
struct I { int a; int b[2]; int c; int d; } __attribute__((designated_init));
struct I i1 = { 1, 2, 3, 4, 5 };
struct I i2 = { 1, { 2, 3 }, 4, 5 };
