// flags: -Wall -Wextra
struct S { int a; const int b; };
struct T { struct S s; int c; };
const int g = 1;
void f(const int p, const struct S cs, struct S *ps, const struct S *cps, struct T t)
{
    const int x = 0;
    int y, arr[3];
    const int ca[3] = {0};
    g = 2;
    x = 3;
    p = 1;
    x++;
    --x;
    g += 1;
    cs.a = 1;
    cs.b = 1;
    ps->b = 2;
    ps->a = 1;
    cps->a = 1;
    t.s = *ps;
    t.s.b = 1;
    t.c = 1;
    *cps = *ps;
    ca[1] = 2;
    arr = 0;
    f = 0;
    1 = y;
    y + 1 = 2;
    (y) = 1;
    (x) = 1;
    y++ = 1;
    ++y = 1;
    y++++;
    3++;
    (y + 1)++;
    -y = 1;
    *(const int *)&y = 1;
    (const int)y = 2;
    y = (void)0;
    y = f(0,cs,0,0,t);
    &y = 0;
    y *= 1.5;
    y <<= 1.5;
    y %= 2.0;
    y += ps;
    ps += 1;
    ps -= ps;
    ps *= 2;
    ps += 1.0;
    y &= ps;
    y |= 1L << 40;
    char ch; ch += 300;
    ch = 300;
    ch <<= 2;
    float fl; fl %= 2;
    fl <<= 1;
    ps <<= 1;
    *ps += 1;
    cs += 1;
    y ^= y;
}
