// flags: -Wall -Wextra
struct S { int a; }; struct T { int a; }; union U { int a; };
typedef void (*fp)(void);
void vf(void); int g1(int); long g2(int); void g3(int, ...);
enum E { A, B };
void f(int i, const int *cp, int *p, void *vp, const void *cvp, volatile int *vip, struct S s, struct S s2, struct T t, union U u, float fl, double d, _Complex double z, enum E e, long l, char *cs, fp fpp, int (*ip)(int), long (*lp)(int), int arr[3], int (*pa)[3], int (*pa4)[4], const struct S cs1, _Bool b)
{
    int r; void *q; const int *cq; struct S rs;
    r = i ? 1 : 2;
    q = i ? p : vp;
    q = i ? cp : vp;
    q = i ? cp : p;
    q = i ? cp : cvp;
    q = i ? p : cvp;
    q = i ? vip : cp;
    q = i ? p : (void *)0;
    q = i ? p : 0;
    q = i ? 0 : p;
    q = i ? p : 1;
    q = i ? p : l;
    q = i ? p : cs;
    q = i ? fpp : vp;
    q = i ? fpp : 0;
    q = i ? ip : lp;
    q = i ? ip : fpp;
    q = i ? vf : vp;
    q = i ? s : s;
    q = i ? s : t;
    q = i ? s : cs1;
    rs = i ? s : s2;
    rs = i ? s : 1;
    r = i ? u : u;
    r = i ? s : i;
    r = i ? z : d;
    r = i ? fl : d;
    r = i ? e : A;
    r = i ? e : l;
    r = i ? b : b;
    r = i ? (void)0 : 1;
    i ? vf() : vf();
    i ? vf() : (void)0;
    r = i ? vf() : i;
    r = i ? arr : p;
    q = i ? pa : pa4;
    q = i ? pa : p;
    r = s ? 1 : 2;
    r = vf ? 1 : 2;
    r = fl ? 1 : 2;
    r = z ? 1 : 2;
    r = i ?: 2;
    r = p ?: 2;
    r = s ?: 2;
    q = i ? p : (const void *)0;
    cq = i ? p : cp;
    q = i ? (int *)0 : (char *)0;
    q = i ? 0 : (char *)0;
    q = i ? (void *)0 : (char *)0;
    q = i ? (const void *)0 : fpp;
    q = i ? (int)0 : fpp;
    q = i ? 0L : p;
    q = i ? 1 - 1 : p;
    q = i ? (char)0 : p;
    q = i ? 0.0 : p;
}
