// flags: -Wall -Wextra
struct S { int a; }; union U { int a; long b; float c; };
typedef void (*fp)(void);
enum E { A, B };
void vf(void);
int arr[3];
void f(int i, long l, char c, float fl, double d, _Complex double z, int *p, char *cp, const int *cip, void *vp, fp fpp, struct S s, union U u, enum E e, _Bool b, short sh)
{
    long r; void *q; struct S rs; union U ru;
    r = (long)s;
    rs = (struct S)s;
    rs = (struct S)i;
    rs = (struct S)u;
    ru = (union U)i;
    ru = (union U)fl;
    ru = (union U)d;
    ru = (union U)l;
    ru = (union U)s;
    ru = (union U)u;
    r = (int)u;
    r = (void)i;
    r = (char)vf;
    r = (char)p;
    r = (short)p;
    q = (void *)fl;
    q = (void *)d;
    q = (int *)fl;
    q = (char *)z;
    r = (long)z;
    r = (int)fpp;
    q = (fp)p;
    q = (fp)vp;
    q = (fp)i;
    q = (fp)fl;
    q = (int *)fpp;
    q = (int *)vf;
    q = (char *)p;
    q = (int *)cip;
    q = (int *)(const int *)p;
    q = (int)p;
    r = (int[3])arr;
    r = (void (*)(void))i;
    r = (_Bool)s;
    r = (_Bool)p;
    r = (_Bool)fl;
    r = (enum E)fl;
    r = (enum E)p;
    r = (float)p;
    r = (double)p;
    r = (float)s;
    r = (_Complex double)i;
    r = (_Complex float)p;
    r = (float)z;
    r = (int)z;
    r = (_Bool)z;
    r = (void *)i;
    r = (void *)sh;
    r = (void *)c;
    r = (void *)e;
    r = (void *)b;
    r = (void *)(short)0;
    r = (char *)l;
    r = (char *)(int)l;
    r = (char *)(unsigned char)l;
    r = (long)(char *)c;
    r = (int *)(char)1;
    rs = (struct S){1};
    rs = (struct S)(struct S){1};
    (void)s;
    (void)vf();
    (struct S *)&s;
    (char)i;
    (int)l, l;
    (const int)i;
    r = (const volatile int)i;
    r = (int *const)p;
    r = (char *const volatile)p;
}
