// flags: -std=c99 -pedantic
#include <stddef.h>
int scanf(const char *, ...);
int sscanf(const char *, const char *, ...);
int fscanf(void *, const char *, ...);
void f(int i, long l, unsigned u, double d, float fl, char *s, int *ip, long *lp, unsigned *up, double *dp, float *fp, short *sp, char *cp, void *p, void **pp, size_t *zp, long long *llp, const int *cip, unsigned char *ucp, wchar_t *wp, char c)
{
  scanf("%d", i);
  scanf("%d", lp);
  scanf("%d", up);
  scanf("%u", ip);
  scanf("%ld", ip);
  scanf("%lf", fp);
  scanf("%f", dp);
  scanf("%lf", dp);
  scanf("%Lf", dp);
  scanf("%s", ip);
  scanf("%s", ucp);
  scanf("%c", cp);
  scanf("%c", ip);
  scanf("%hd", ip);
  scanf("%hd", sp);
  scanf("%hhd", cp);
  scanf("%zu", zp);
  scanf("%zu", lp);
  scanf("%lld", lp);
  scanf("%p", pp);
  scanf("%p", ip);
  scanf("%d", cip);
  scanf("%d");
  scanf("%d %d", ip);
  scanf("%d", ip, ip);
  scanf("%*d");
  scanf("%*d", ip);
  scanf("%5d", ip);
  scanf("%.2d", ip);
  scanf("%[a-z]", cp);
  scanf("%[a-z]", ip);
  scanf("%[a-z", cp);
  scanf("%n", ip);
  scanf("%n", lp);
  scanf("%ls", wp);
  scanf("%ls", cp);
  scanf("%y", ip);
  scanf("%", ip);
  scanf("%d%%", ip);
  scanf("%i %o %x %X %e %g %a", ip, ip, ip, ip, fp, fp, fp);
  scanf("%i", up);
  scanf("%o", ip);
  scanf("%'d", ip);
  scanf("%+d", ip);
  scanf("%m", cp);
  scanf("%ms", &cp);
  scanf("%ms", cp);
  scanf("%as", cp);
  sscanf(s, "%d", d);
  fscanf(p, "%d", lp);
  scanf("");
  scanf("%d", 0);
  scanf("%s", 0);
  scanf("%lc", wp);
  scanf("%C", wp);
  scanf("%S", wp);
  scanf("%1$d", ip);
  scanf("%hs", cp);
  scanf("%lp", pp);
  scanf("%d", &i);
  scanf("%d", &l);
  scanf("%s", &s);
  scanf("%s", s);
  scanf("%f", &fl);
  scanf("%d", (int *)p);
}
