typedef const struct S *SRef;
int a1 (unsigned char *f, ...) __attribute__((format(printf, 1, 2)));
int a2 (const char *const *f, ...) __attribute__((format(printf, 1, 2)));
int a3 (const char *volatile f, ...) __attribute__((format(printf, 1, 2)));
int a4 (SRef f, ...) __attribute__((format(printf, 1, 2)));
int a5 (long f, ...) __attribute__((format(printf, 1, 2)));
int a6 (const char *f, int d) __attribute__((format(printf, 1, 3)));
int a7 (const char *f, ...) __attribute__((format(printf, 1, 4)));
int a8 (const char *f, int d, ...) __attribute__((format(printf, 1, 2)));
int a9 (const char *f, int d, ...) __attribute__((format(printf, 1, 3)));
int b1 (const char *f, int d) __attribute__((format(printf, 3, 4)));
int b2 (const char *f, ...) __attribute__((format(strftime, 1, 2)));
int b3 (const char *f, ...) __attribute__((format(strftime, 1, 0)));
int b4 () __attribute__((format(printf, 1, 2)));
int b5 (const char *f, ...) __attribute__((format(printf, 1, 1)));
int b6 (const char *f, ...) __attribute__((format(printf, 1, 1.0)));
int b7 (const char *f, ...) __attribute__((format(NoSuchKind, 1, 2)));
int c1 (int f) __attribute__((format_arg(1)));
char *c2 (SRef f) __attribute__((format_arg(1)));
const char *c3 (const char *f) __attribute__((format_arg(1)));
unsigned char *c4 (const char *f) __attribute__((format_arg(1)));
int c5 (const char *f) __attribute__((format_arg(1)));
int c6 () __attribute__((format_arg(1)));
int c7 (int d, char *f) __attribute__((format_arg(d)));
