// flags: -Wall -Wextra
const int k = 5;
int z = k;
int w = sizeof(int) + 1;
int *p1 = &z;
long p2 = (long)&z;
char p3 = (char)&z;
int *p4 = (int*)(long)&z;
int arr[3];
int *p5 = arr + 1;
int *p6 = &arr[2];
int *p7 = (int[]){1,2};
double d1 = 1 + 2.0;
int i1 = 1.5;
int i2 = (int)1.5;
int i3 = 1 ? 2 : z;
int i4 = z ? 2 : 3;
int i5 = (z, 2);
void f(void);
void (*fp)(void) = f;
void (*fp2)(void) = &f;
char *s1 = "abc";
char *s2 = "abc" + 1;
int i6 = "abc";
int *i7 = &z + 1;
long i8 = &z - &z;
int i9 = &arr[1] - &arr[0];
struct S { int a; int b[2]; } sv;
int *i10 = &sv.b[1];
int i11 = sizeof(z);
int i12 = z++;
int i13 = f;
