/* cbuiltin_tab.h - gcc 13's library built-ins visible under -std=c99 that a
 * call without a declaration can reach: name, the header gcc suggests,
 * whether the implicit declaration int() mismatches the built-in's type,
 * and the type "return|param|param..." ("?": declared without prototype).
 * Sorted by name.  Generated from gcc's own diagnostics. */
static const struct { const char *name, *hdr; unsigned char mismatch; const char *sig; } cbuiltin_tab[] = {
    {"abort", "<stdlib.h>", 1, "void|"},
    {"abs", "<stdlib.h>", 0, "int|int"},
    {"acos", "<math.h>", 1, "double|double"},
    {"acosf", "<math.h>", 1, "float|float"},
    {"acosh", "<math.h>", 1, "double|double"},
    {"acoshf", "<math.h>", 1, "float|float"},
    {"acoshl", "<math.h>", 1, "long double|long double"},
    {"acosl", "<math.h>", 1, "long double|long double"},
    {"asin", "<math.h>", 1, "double|double"},
    {"asinf", "<math.h>", 1, "float|float"},
    {"asinh", "<math.h>", 1, "double|double"},
    {"asinhf", "<math.h>", 1, "float|float"},
    {"asinhl", "<math.h>", 1, "long double|long double"},
    {"asinl", "<math.h>", 1, "long double|long double"},
    {"atan", "<math.h>", 1, "double|double"},
    {"atan2", "<math.h>", 1, "double|double|double"},
    {"atan2f", "<math.h>", 1, "float|float|float"},
    {"atan2l", "<math.h>", 1, "long double|long double|long double"},
    {"atanf", "<math.h>", 1, "float|float"},
    {"atanh", "<math.h>", 1, "double|double"},
    {"atanhf", "<math.h>", 1, "float|float"},
    {"atanhl", "<math.h>", 1, "long double|long double"},
    {"atanl", "<math.h>", 1, "long double|long double"},
    {"cacos", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"cacosf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"cacosh", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"cacoshf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"cacoshl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"cacosl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"calloc", "<stdlib.h>", 1, "void *|long unsigned int|long unsigned int"},
    {"casin", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"casinf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"casinh", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"casinhf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"casinhl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"casinl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"catan", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"catanf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"catanh", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"catanhf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"catanhl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"catanl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"cbrt", "<math.h>", 1, "double|double"},
    {"cbrtf", "<math.h>", 1, "float|float"},
    {"cbrtl", "<math.h>", 1, "long double|long double"},
    {"ccos", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"ccosf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"ccosh", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"ccoshf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"ccoshl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"ccosl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"ceil", "<math.h>", 1, "double|double"},
    {"ceilf", "<math.h>", 1, "float|float"},
    {"ceill", "<math.h>", 1, "long double|long double"},
    {"cexp", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"cexpf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"cexpl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"clog", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"clogf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"clogl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"conj", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"conjf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"conjl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"copysign", "<math.h>", 1, "double|double|double"},
    {"copysignf", "<math.h>", 1, "float|float|float"},
    {"copysignl", "<math.h>", 1, "long double|long double|long double"},
    {"cos", "<math.h>", 1, "double|double"},
    {"cosf", "<math.h>", 1, "float|float"},
    {"cosh", "<math.h>", 1, "double|double"},
    {"coshf", "<math.h>", 1, "float|float"},
    {"coshl", "<math.h>", 1, "long double|long double"},
    {"cosl", "<math.h>", 1, "long double|long double"},
    {"cpow", "<complex.h>", 1, "_Complex double|_Complex double|_Complex double"},
    {"cpowf", "<complex.h>", 1, "_Complex float|_Complex float|_Complex float"},
    {"cpowl", "<complex.h>", 1, "_Complex long double|_Complex long double|_Complex long double"},
    {"cproj", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"cprojf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"cprojl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"csin", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"csinf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"csinh", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"csinhf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"csinhl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"csinl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"csqrt", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"csqrtf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"csqrtl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"ctan", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"ctanf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"ctanh", "<complex.h>", 1, "_Complex double|_Complex double"},
    {"ctanhf", "<complex.h>", 1, "_Complex float|_Complex float"},
    {"ctanhl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"ctanl", "<complex.h>", 1, "_Complex long double|_Complex long double"},
    {"erf", "<math.h>", 1, "double|double"},
    {"erfc", "<math.h>", 1, "double|double"},
    {"erfcf", "<math.h>", 1, "float|float"},
    {"erfcl", "<math.h>", 1, "long double|long double"},
    {"erff", "<math.h>", 1, "float|float"},
    {"erfl", "<math.h>", 1, "long double|long double"},
    {"exit", "<stdlib.h>", 1, "void|int"},
    {"exp", "<math.h>", 1, "double|double"},
    {"exp2", "<math.h>", 1, "double|double"},
    {"exp2f", "<math.h>", 1, "float|float"},
    {"exp2l", "<math.h>", 1, "long double|long double"},
    {"expf", "<math.h>", 1, "float|float"},
    {"expl", "<math.h>", 1, "long double|long double"},
    {"expm1", "<math.h>", 1, "double|double"},
    {"expm1f", "<math.h>", 1, "float|float"},
    {"expm1l", "<math.h>", 1, "long double|long double"},
    {"fabs", "<math.h>", 1, "double|double"},
    {"fabsf", "<math.h>", 1, "float|float"},
    {"fabsl", "<math.h>", 1, "long double|long double"},
    {"fdim", "<math.h>", 1, "double|double|double"},
    {"fdimf", "<math.h>", 1, "float|float|float"},
    {"fdiml", "<math.h>", 1, "long double|long double|long double"},
    {"floor", "<math.h>", 1, "double|double"},
    {"floorf", "<math.h>", 1, "float|float"},
    {"floorl", "<math.h>", 1, "long double|long double"},
    {"fma", "<math.h>", 1, "double|double|double|double"},
    {"fmaf", "<math.h>", 1, "float|float|float|float"},
    {"fmal", "<math.h>", 1, "long double|long double|long double|long double"},
    {"fmax", "<math.h>", 1, "double|double|double"},
    {"fmaxf", "<math.h>", 1, "float|float|float"},
    {"fmaxl", "<math.h>", 1, "long double|long double|long double"},
    {"fmin", "<math.h>", 1, "double|double|double"},
    {"fminf", "<math.h>", 1, "float|float|float"},
    {"fminl", "<math.h>", 1, "long double|long double|long double"},
    {"fmod", "<math.h>", 1, "double|double|double"},
    {"fmodf", "<math.h>", 1, "float|float|float"},
    {"fmodl", "<math.h>", 1, "long double|long double|long double"},
    {"fprintf", "<stdio.h>", 1, "int|void *|const char *|..."},
    {"fputc", "<stdio.h>", 0, "int|int|void *"},
    {"fputs", "<stdio.h>", 0, "int|const char *|void *"},
    {"free", "<stdlib.h>", 1, "void|void *"},
    {"frexp", "<math.h>", 1, "double|double|int *"},
    {"frexpf", "<math.h>", 1, "float|float|int *"},
    {"frexpl", "<math.h>", 1, "long double|long double|int *"},
    {"fscanf", "<stdio.h>", 1, "int|void *|const char *|..."},
    {"fwrite", "<stdio.h>", 1, "long unsigned int|const void *|long unsigned int|long unsigned int|void *"},
    {"hypot", "<math.h>", 1, "double|double|double"},
    {"hypotf", "<math.h>", 1, "float|float|float"},
    {"hypotl", "<math.h>", 1, "long double|long double|long double"},
    {"ilogb", "<math.h>", 0, "int|double"},
    {"imaxabs", "<inttypes.h>", 1, "long int|long int"},
    {"isalnum", "<ctype.h>", 0, "int|int"},
    {"isalpha", "<ctype.h>", 0, "int|int"},
    {"isblank", "<ctype.h>", 0, "int|int"},
    {"iscntrl", "<ctype.h>", 0, "int|int"},
    {"isdigit", "<ctype.h>", 0, "int|int"},
    {"isgraph", "<ctype.h>", 0, "int|int"},
    {"isinf", "<math.h>", 0, "int|?"},
    {"islower", "<ctype.h>", 0, "int|int"},
    {"isnan", "<math.h>", 0, "int|?"},
    {"isprint", "<ctype.h>", 0, "int|int"},
    {"ispunct", "<ctype.h>", 0, "int|int"},
    {"isspace", "<ctype.h>", 0, "int|int"},
    {"isupper", "<ctype.h>", 0, "int|int"},
    {"isxdigit", "<ctype.h>", 0, "int|int"},
    {"labs", "<stdlib.h>", 1, "long int|long int"},
    {"ldexp", "<math.h>", 1, "double|double|int"},
    {"ldexpf", "<math.h>", 1, "float|float|int"},
    {"ldexpl", "<math.h>", 1, "long double|long double|int"},
    {"lgamma", "<math.h>", 1, "double|double"},
    {"lgammaf", "<math.h>", 1, "float|float"},
    {"lgammal", "<math.h>", 1, "long double|long double"},
    {"llabs", "<stdlib.h>", 1, "long long int|long long int"},
    {"log", "<math.h>", 1, "double|double"},
    {"log10", "<math.h>", 1, "double|double"},
    {"log10f", "<math.h>", 1, "float|float"},
    {"log10l", "<math.h>", 1, "long double|long double"},
    {"log1p", "<math.h>", 1, "double|double"},
    {"log1pf", "<math.h>", 1, "float|float"},
    {"log1pl", "<math.h>", 1, "long double|long double"},
    {"log2", "<math.h>", 1, "double|double"},
    {"log2f", "<math.h>", 1, "float|float"},
    {"log2l", "<math.h>", 1, "long double|long double"},
    {"logb", "<math.h>", 1, "double|double"},
    {"logbf", "<math.h>", 1, "float|float"},
    {"logbl", "<math.h>", 1, "long double|long double"},
    {"logf", "<math.h>", 1, "float|float"},
    {"logl", "<math.h>", 1, "long double|long double"},
    {"malloc", "<stdlib.h>", 1, "void *|long unsigned int"},
    {"memchr", "<string.h>", 1, "void *|const void *|int|long unsigned int"},
    {"memcmp", "<string.h>", 0, "int|const void *|const void *|long unsigned int"},
    {"memcpy", "<string.h>", 1, "void *|void *|const void *|long unsigned int"},
    {"memmove", "<string.h>", 1, "void *|void *|const void *|long unsigned int"},
    {"memset", "<string.h>", 1, "void *|void *|int|long unsigned int"},
    {"modf", "<math.h>", 1, "double|double|double *"},
    {"modff", "<math.h>", 1, "float|float|float *"},
    {"modfl", "<math.h>", 1, "long double|long double|long double *"},
    {"nan", "<math.h>", 1, "double|const char *"},
    {"nanf", "<math.h>", 1, "float|const char *"},
    {"nanl", "<math.h>", 1, "long double|const char *"},
    {"nearbyint", "<math.h>", 1, "double|double"},
    {"nearbyintf", "<math.h>", 1, "float|float"},
    {"nearbyintl", "<math.h>", 1, "long double|long double"},
    {"nextafter", "<math.h>", 1, "double|double|double"},
    {"nextafterf", "<math.h>", 1, "float|float|float"},
    {"nextafterl", "<math.h>", 1, "long double|long double|long double"},
    {"nexttoward", "<math.h>", 1, "double|double|long double"},
    {"nexttowardf", "<math.h>", 1, "float|float|long double"},
    {"nexttowardl", "<math.h>", 1, "long double|long double|long double"},
    {"pow", "<math.h>", 1, "double|double|double"},
    {"powf", "<math.h>", 1, "float|float|float"},
    {"powl", "<math.h>", 1, "long double|long double|long double"},
    {"printf", "<stdio.h>", 1, "int|const char *|..."},
    {"putc", "<stdio.h>", 0, "int|int|void *"},
    {"putchar", "<stdio.h>", 0, "int|int"},
    {"puts", "<stdio.h>", 0, "int|const char *"},
    {"realloc", "<stdlib.h>", 1, "void *|void *|long unsigned int"},
    {"remainder", "<math.h>", 1, "double|double|double"},
    {"remainderf", "<math.h>", 1, "float|float|float"},
    {"remainderl", "<math.h>", 1, "long double|long double|long double"},
    {"remquo", "<math.h>", 1, "double|double|double|int *"},
    {"remquof", "<math.h>", 1, "float|float|float|int *"},
    {"remquol", "<math.h>", 1, "long double|long double|long double|int *"},
    {"rint", "<math.h>", 1, "double|double"},
    {"rintf", "<math.h>", 1, "float|float"},
    {"rintl", "<math.h>", 1, "long double|long double"},
    {"round", "<math.h>", 1, "double|double"},
    {"roundf", "<math.h>", 1, "float|float"},
    {"roundl", "<math.h>", 1, "long double|long double"},
    {"scalbln", "<math.h>", 1, "double|double|long int"},
    {"scalblnf", "<math.h>", 1, "float|float|long int"},
    {"scalblnl", "<math.h>", 1, "long double|long double|long int"},
    {"scalbn", "<math.h>", 1, "double|double|int"},
    {"scalbnf", "<math.h>", 1, "float|float|int"},
    {"scalbnl", "<math.h>", 1, "long double|long double|int"},
    {"scanf", "<stdio.h>", 1, "int|const char *|..."},
    {"sin", "<math.h>", 1, "double|double"},
    {"sinf", "<math.h>", 1, "float|float"},
    {"sinh", "<math.h>", 1, "double|double"},
    {"sinhf", "<math.h>", 1, "float|float"},
    {"sinhl", "<math.h>", 1, "long double|long double"},
    {"sinl", "<math.h>", 1, "long double|long double"},
    {"snprintf", "<stdio.h>", 1, "int|char *|long unsigned int|const char *|..."},
    {"sprintf", "<stdio.h>", 1, "int|char *|const char *|..."},
    {"sqrt", "<math.h>", 1, "double|double"},
    {"sqrtf", "<math.h>", 1, "float|float"},
    {"sqrtl", "<math.h>", 1, "long double|long double"},
    {"sscanf", "<stdio.h>", 1, "int|const char *|const char *|..."},
    {"strcat", "<string.h>", 1, "char *|char *|const char *"},
    {"strchr", "<string.h>", 1, "char *|const char *|int"},
    {"strcmp", "<string.h>", 0, "int|const char *|const char *"},
    {"strcpy", "<string.h>", 1, "char *|char *|const char *"},
    {"strcspn", "<string.h>", 1, "long unsigned int|const char *|const char *"},
    {"strftime", "<time.h>", 1, "long unsigned int|char *|long unsigned int|const char *|const void *"},
    {"strlen", "<string.h>", 1, "long unsigned int|const char *"},
    {"strncat", "<string.h>", 1, "char *|char *|const char *|long unsigned int"},
    {"strncmp", "<string.h>", 0, "int|const char *|const char *|long unsigned int"},
    {"strncpy", "<string.h>", 1, "char *|char *|const char *|long unsigned int"},
    {"strpbrk", "<string.h>", 1, "char *|const char *|const char *"},
    {"strrchr", "<string.h>", 1, "char *|const char *|int"},
    {"strspn", "<string.h>", 1, "long unsigned int|const char *|const char *"},
    {"strstr", "<string.h>", 1, "char *|const char *|const char *"},
    {"tan", "<math.h>", 1, "double|double"},
    {"tanf", "<math.h>", 1, "float|float"},
    {"tanh", "<math.h>", 1, "double|double"},
    {"tanhf", "<math.h>", 1, "float|float"},
    {"tanhl", "<math.h>", 1, "long double|long double"},
    {"tanl", "<math.h>", 1, "long double|long double"},
    {"tgamma", "<math.h>", 1, "double|double"},
    {"tgammaf", "<math.h>", 1, "float|float"},
    {"tgammal", "<math.h>", 1, "long double|long double"},
    {"tolower", "<ctype.h>", 0, "int|int"},
    {"toupper", "<ctype.h>", 0, "int|int"},
    {"trunc", "<math.h>", 1, "double|double"},
    {"truncf", "<math.h>", 1, "float|float"},
    {"truncl", "<math.h>", 1, "long double|long double"},
    {"vfprintf", "<stdio.h>", 0, "int|void *|const char *|__va_list_tag *"},
    {"vfscanf", "<stdio.h>", 0, "int|void *|const char *|__va_list_tag *"},
    {"vprintf", "<stdio.h>", 0, "int|const char *|__va_list_tag *"},
    {"vscanf", "<stdio.h>", 0, "int|const char *|__va_list_tag *"},
    {"vsnprintf", "<stdio.h>", 0, "int|char *|long unsigned int|const char *|__va_list_tag *"},
    {"vsprintf", "<stdio.h>", 0, "int|char *|const char *|__va_list_tag *"},
    {"vsscanf", "<stdio.h>", 0, "int|const char *|const char *|__va_list_tag *"},
};
