/* cbuiltin_tab.h - gcc 13's library built-ins visible under -std=c99 that a
 * call without a declaration can reach: name, the header gcc suggests,
 * whether the implicit declaration int() mismatches the built-in's type,
 * and the type "return|param|param..." ("?": declared without prototype).
 * Entries with gnu = 1 (empty header: gcc names none) exist only without
 * -std=c99; see bench/tools/gen_builtin_gnu.py.
 * (__clear_cache is gnu = 1 by hand: gen_builtin_gnu.py skips _-prefixed names.)
 * Entries with gnu = 2 exist only as __builtin_NAME (bench/tools/gen_builtin_pfx.py,
 * filtered to types bt_type parses by bench/tools/merge_builtin_pfx.py).
 * Sorted by name.  Generated from gcc's own diagnostics. */
static const struct { const char *name, *hdr; unsigned char mismatch; const char *sig; unsigned char gnu; } cbuiltin_tab[] = {
    {"FILE", "", 0, "const char *|", 2},
    {"FUNCTION", "", 0, "const char *|", 2},
    {"LINE", "", 0, "int|", 2},
    {"__clear_cache", "", 0, "void|void *|void *", 1},
    {"abort", "<stdlib.h>", 1, "void|", 0},
    {"abs", "<stdlib.h>", 0, "int|int", 0},
    {"acc_on_device", "", 0, "int|int", 2},
    {"acos", "<math.h>", 1, "double|double", 0},
    {"acosf", "<math.h>", 1, "float|float", 0},
    {"acosh", "<math.h>", 1, "double|double", 0},
    {"acoshf", "<math.h>", 1, "float|float", 0},
    {"acoshl", "<math.h>", 1, "long double|long double", 0},
    {"acosl", "<math.h>", 1, "long double|long double", 0},
    {"adjust_descriptor", "", 0, "void *|void *", 2},
    {"adjust_trampoline", "", 0, "void *|void *", 2},
    {"aggregate_incoming_address", "", 0, "void *|", 2},
    {"aligned_alloc", "", 1, "void *|long unsigned int|long unsigned int", 1},
    {"alloca", "", 1, "void *|long unsigned int", 1},
    {"alloca_with_align", "", 0, "void *|long unsigned int|long unsigned int", 2},
    {"alloca_with_align_and_max", "", 0, "void *|long unsigned int|long unsigned int|long unsigned int", 2},
    {"apply_args", "", 0, "void *|", 2},
    {"asin", "<math.h>", 1, "double|double", 0},
    {"asinf", "<math.h>", 1, "float|float", 0},
    {"asinh", "<math.h>", 1, "double|double", 0},
    {"asinhf", "<math.h>", 1, "float|float", 0},
    {"asinhl", "<math.h>", 1, "long double|long double", 0},
    {"asinl", "<math.h>", 1, "long double|long double", 0},
    {"assume_aligned", "", 0, "void *|const void *|long unsigned int|...", 2},
    {"atan", "<math.h>", 1, "double|double", 0},
    {"atan2", "<math.h>", 1, "double|double|double", 0},
    {"atan2f", "<math.h>", 1, "float|float|float", 0},
    {"atan2l", "<math.h>", 1, "long double|long double|long double", 0},
    {"atanf", "<math.h>", 1, "float|float", 0},
    {"atanh", "<math.h>", 1, "double|double", 0},
    {"atanhf", "<math.h>", 1, "float|float", 0},
    {"atanhl", "<math.h>", 1, "long double|long double", 0},
    {"atanl", "<math.h>", 1, "long double|long double", 0},
    {"bcmp", "", 0, "int|const void *|const void *|long unsigned int", 1},
    {"bcopy", "", 1, "void|const void *|void *|long unsigned int", 1},
    {"bswap128", "", 0, "__int128 unsigned|__int128 unsigned", 2},
    {"bswap16", "", 0, "short unsigned int|short unsigned int", 2},
    {"bswap32", "", 0, "unsigned int|unsigned int", 2},
    {"bswap64", "", 0, "long unsigned int|long unsigned int", 2},
    {"bzero", "", 1, "void|void *|long unsigned int", 1},
    {"cacos", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"cacosf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"cacosh", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"cacoshf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"cacoshl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"cacosl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"calloc", "<stdlib.h>", 1, "void *|long unsigned int|long unsigned int", 0},
    {"casin", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"casinf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"casinh", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"casinhf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"casinhl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"casinl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"catan", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"catanf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"catanh", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"catanhf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"catanhl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"catanl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"cbrt", "<math.h>", 1, "double|double", 0},
    {"cbrtf", "<math.h>", 1, "float|float", 0},
    {"cbrtl", "<math.h>", 1, "long double|long double", 0},
    {"ccos", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"ccosf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"ccosh", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"ccoshf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"ccoshl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"ccosl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"ceil", "<math.h>", 1, "double|double", 0},
    {"ceilf", "<math.h>", 1, "float|float", 0},
    {"ceill", "<math.h>", 1, "long double|long double", 0},
    {"cexp", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"cexpf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"cexpi", "", 0, "_Complex double|double", 2},
    {"cexpif", "", 0, "_Complex float|float", 2},
    {"cexpil", "", 0, "_Complex long double|long double", 2},
    {"cexpl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"classify_type", "", 0, "int|", 2},
    {"clog", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"clog10", "", 1, "_Complex double|_Complex double", 1},
    {"clog10f", "", 1, "_Complex float|_Complex float", 1},
    {"clog10l", "", 1, "_Complex long double|_Complex long double", 1},
    {"clogf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"clogl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"clrsb", "", 0, "int|int", 2},
    {"clrsbimax", "", 0, "int|long int", 2},
    {"clrsbl", "", 0, "int|long int", 2},
    {"clrsbll", "", 0, "int|long long int", 2},
    {"clz", "", 0, "int|unsigned int", 2},
    {"clzimax", "", 0, "int|long unsigned int", 2},
    {"clzl", "", 0, "int|long unsigned int", 2},
    {"clzll", "", 0, "int|long long unsigned int", 2},
    {"conj", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"conjf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"conjl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"constant_p", "", 0, "int|", 2},
    {"copysign", "<math.h>", 1, "double|double|double", 0},
    {"copysignf", "<math.h>", 1, "float|float|float", 0},
    {"copysignl", "<math.h>", 1, "long double|long double|long double", 0},
    {"copysignq", "", 0, "__float128|__float128|__float128", 3},
    {"cos", "<math.h>", 1, "double|double", 0},
    {"cosf", "<math.h>", 1, "float|float", 0},
    {"cosh", "<math.h>", 1, "double|double", 0},
    {"coshf", "<math.h>", 1, "float|float", 0},
    {"coshl", "<math.h>", 1, "long double|long double", 0},
    {"cosl", "<math.h>", 1, "long double|long double", 0},
    {"cpow", "<complex.h>", 1, "_Complex double|_Complex double|_Complex double", 0},
    {"cpowf", "<complex.h>", 1, "_Complex float|_Complex float|_Complex float", 0},
    {"cpowl", "<complex.h>", 1, "_Complex long double|_Complex long double|_Complex long double", 0},
    {"cproj", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"cprojf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"cprojl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"csin", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"csinf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"csinh", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"csinhf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"csinhl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"csinl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"csqrt", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"csqrtf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"csqrtl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"ctan", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"ctanf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"ctanh", "<complex.h>", 1, "_Complex double|_Complex double", 0},
    {"ctanhf", "<complex.h>", 1, "_Complex float|_Complex float", 0},
    {"ctanhl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"ctanl", "<complex.h>", 1, "_Complex long double|_Complex long double", 0},
    {"ctz", "", 0, "int|unsigned int", 2},
    {"ctzimax", "", 0, "int|long unsigned int", 2},
    {"ctzl", "", 0, "int|long unsigned int", 2},
    {"ctzll", "", 0, "int|long long unsigned int", 2},
    {"dcgettext", "", 1, "char *|const char *|const char *|int", 1},
    {"dgettext", "", 1, "char *|const char *|const char *", 1},
    {"drem", "", 1, "double|double|double", 1},
    {"dremf", "", 1, "float|float|float", 1},
    {"dreml", "", 1, "long double|long double|long double", 1},
    {"dwarf_cfa", "", 0, "void *|", 2},
    {"dwarf_sp_column", "", 0, "unsigned int|", 2},
    {"dynamic_object_size", "", 0, "long unsigned int|const void *|int", 2},
    {"eh_copy_values", "", 0, "void|int|int", 2},
    {"eh_filter", "", 0, "long int|int", 2},
    {"eh_pointer", "", 0, "void *|int", 2},
    {"eh_return", "", 0, "void|long int|void *", 2},
    {"eh_return_data_regno", "", 0, "int|int", 2},
    {"erf", "<math.h>", 1, "double|double", 0},
    {"erfc", "<math.h>", 1, "double|double", 0},
    {"erfcf", "<math.h>", 1, "float|float", 0},
    {"erfcl", "<math.h>", 1, "long double|long double", 0},
    {"erff", "<math.h>", 1, "float|float", 0},
    {"erfl", "<math.h>", 1, "long double|long double", 0},
    {"execl", "", 1, "int|const char *|const char *|...", 1},
    {"execle", "", 1, "int|const char *|const char *|...", 1},
    {"execlp", "", 1, "int|const char *|const char *|...", 1},
    {"exit", "<stdlib.h>", 1, "void|int", 0},
    {"exp", "<math.h>", 1, "double|double", 0},
    {"exp10", "", 1, "double|double", 1},
    {"exp10f", "", 1, "float|float", 1},
    {"exp10l", "", 1, "long double|long double", 1},
    {"exp2", "<math.h>", 1, "double|double", 0},
    {"exp2f", "<math.h>", 1, "float|float", 0},
    {"exp2l", "<math.h>", 1, "long double|long double", 0},
    {"expect", "", 0, "long int|long int|long int", 2},
    {"expect_with_probability", "", 0, "long int|long int|long int|double", 2},
    {"expf", "<math.h>", 1, "float|float", 0},
    {"expl", "<math.h>", 1, "long double|long double", 0},
    {"expm1", "<math.h>", 1, "double|double", 0},
    {"expm1f", "<math.h>", 1, "float|float", 0},
    {"expm1l", "<math.h>", 1, "long double|long double", 0},
    {"extend_pointer", "", 0, "long unsigned int|void *", 2},
    {"extract_return_addr", "", 0, "void *|void *", 2},
    {"fabs", "<math.h>", 1, "double|double", 0},
    {"fabsf", "<math.h>", 1, "float|float", 0},
    {"fabsl", "<math.h>", 1, "long double|long double", 0},
    {"fabsq", "", 0, "__float128|__float128", 3},
    {"fdim", "<math.h>", 1, "double|double|double", 0},
    {"fdimf", "<math.h>", 1, "float|float|float", 0},
    {"fdiml", "<math.h>", 1, "long double|long double|long double", 0},
    {"ffs", "", 0, "int|int", 1},
    {"ffsimax", "", 0, "int|long int", 1},
    {"ffsl", "", 0, "int|long int", 1},
    {"ffsll", "", 0, "int|long long int", 1},
    {"finite", "", 0, "int|double", 1},
    {"finitef", "", 1, "int|float", 1},
    {"finitel", "", 0, "int|long double", 1},
    {"floor", "<math.h>", 1, "double|double", 0},
    {"floorf", "<math.h>", 1, "float|float", 0},
    {"floorl", "<math.h>", 1, "long double|long double", 0},
    {"fma", "<math.h>", 1, "double|double|double|double", 0},
    {"fmaf", "<math.h>", 1, "float|float|float|float", 0},
    {"fmal", "<math.h>", 1, "long double|long double|long double|long double", 0},
    {"fmax", "<math.h>", 1, "double|double|double", 0},
    {"fmaxf", "<math.h>", 1, "float|float|float", 0},
    {"fmaxl", "<math.h>", 1, "long double|long double|long double", 0},
    {"fmin", "<math.h>", 1, "double|double|double", 0},
    {"fminf", "<math.h>", 1, "float|float|float", 0},
    {"fminl", "<math.h>", 1, "long double|long double|long double", 0},
    {"fmod", "<math.h>", 1, "double|double|double", 0},
    {"fmodf", "<math.h>", 1, "float|float|float", 0},
    {"fmodl", "<math.h>", 1, "long double|long double|long double", 0},
    {"fork", "", 0, "int|", 1},
    {"fpclassify", "", 0, "int|int|int|int|int|int|...", 2},
    {"fprintf", "<stdio.h>", 1, "int|void *|const char *|...", 0},
    {"fprintf_unlocked", "", 1, "int|void *|const char *|...", 1},
    {"fputc", "<stdio.h>", 0, "int|int|void *", 0},
    {"fputc_unlocked", "", 0, "int|int|void *", 1},
    {"fputs", "<stdio.h>", 0, "int|const char *|void *", 0},
    {"fputs_unlocked", "", 0, "int|const char *|void *", 1},
    {"frame_address", "", 0, "void *|unsigned int", 2},
    {"free", "<stdlib.h>", 1, "void|void *", 0},
    {"frexp", "<math.h>", 1, "double|double|int *", 0},
    {"frexpf", "<math.h>", 1, "float|float|int *", 0},
    {"frexpl", "<math.h>", 1, "long double|long double|int *", 0},
    {"frob_return_addr", "", 0, "void *|void *", 2},
    {"fscanf", "<stdio.h>", 1, "int|void *|const char *|...", 0},
    {"fwrite", "<stdio.h>", 1, "long unsigned int|const void *|long unsigned int|long unsigned int|void *", 0},
    {"fwrite_unlocked", "", 1, "long unsigned int|const void *|long unsigned int|long unsigned int|void *", 1},
    {"gamma", "", 1, "double|double", 1},
    {"gamma_r", "", 1, "double|double|int *", 1},
    {"gammaf", "", 1, "float|float", 1},
    {"gammaf_r", "", 1, "float|float|int *", 1},
    {"gammal", "", 1, "long double|long double", 1},
    {"gammal_r", "", 1, "long double|long double|int *", 1},
    {"gettext", "", 1, "char *|const char *", 1},
    {"huge_val", "", 0, "double|", 2},
    {"huge_valf", "", 0, "float|", 2},
    {"huge_vall", "", 0, "long double|", 2},
    {"huge_valq", "", 0, "__float128|", 3},
    {"hypot", "<math.h>", 1, "double|double|double", 0},
    {"hypotf", "<math.h>", 1, "float|float|float", 0},
    {"hypotl", "<math.h>", 1, "long double|long double|long double", 0},
    {"iceil", "", 0, "int|double", 2},
    {"iceilf", "", 0, "int|float", 2},
    {"iceill", "", 0, "int|long double", 2},
    {"ifloor", "", 0, "int|double", 2},
    {"ifloorf", "", 0, "int|float", 2},
    {"ifloorl", "", 0, "int|long double", 2},
    {"ilogb", "<math.h>", 0, "int|double", 0},
    {"imaxabs", "<inttypes.h>", 1, "long int|long int", 0},
    {"index", "", 1, "char *|const char *|int", 1},
    {"inf", "", 0, "double|", 2},
    {"inff", "", 0, "float|", 2},
    {"infl", "", 0, "long double|", 2},
    {"infq", "", 0, "__float128|", 3},
    {"init_descriptor", "", 0, "void|void *|void *|void *", 2},
    {"init_dwarf_reg_size_table", "", 0, "void|void *", 2},
    {"init_heap_trampoline", "", 0, "void|void *|void *|void *", 2},
    {"init_trampoline", "", 0, "void|void *|void *|void *", 2},
    {"irint", "", 0, "int|double", 2},
    {"irintf", "", 0, "int|float", 2},
    {"irintl", "", 0, "int|long double", 2},
    {"iround", "", 0, "int|double", 2},
    {"iroundf", "", 0, "int|float", 2},
    {"iroundl", "", 0, "int|long double", 2},
    {"isalnum", "<ctype.h>", 0, "int|int", 0},
    {"isalpha", "<ctype.h>", 0, "int|int", 0},
    {"isascii", "", 0, "int|int", 1},
    {"isblank", "<ctype.h>", 0, "int|int", 0},
    {"iscntrl", "<ctype.h>", 0, "int|int", 0},
    {"isdigit", "<ctype.h>", 0, "int|int", 0},
    {"isfinite", "", 0, "int|", 2},
    {"isgraph", "<ctype.h>", 0, "int|int", 0},
    {"isinf", "<math.h>", 0, "int|?", 0},
    {"isinf_sign", "", 0, "int|", 2},
    {"isinff", "", 1, "int|float", 1},
    {"isinfl", "", 0, "int|long double", 1},
    {"islower", "<ctype.h>", 0, "int|int", 0},
    {"isnan", "<math.h>", 0, "int|?", 0},
    {"isnanf", "", 1, "int|float", 1},
    {"isnanl", "", 0, "int|long double", 1},
    {"isnormal", "", 0, "int|", 2},
    {"isprint", "<ctype.h>", 0, "int|int", 0},
    {"ispunct", "<ctype.h>", 0, "int|int", 0},
    {"issignaling", "", 0, "int|", 2},
    {"isspace", "<ctype.h>", 0, "int|int", 0},
    {"isupper", "<ctype.h>", 0, "int|int", 0},
    {"isxdigit", "<ctype.h>", 0, "int|int", 0},
    {"j0", "", 1, "double|double", 1},
    {"j0f", "", 1, "float|float", 1},
    {"j0l", "", 1, "long double|long double", 1},
    {"j1", "", 1, "double|double", 1},
    {"j1f", "", 1, "float|float", 1},
    {"j1l", "", 1, "long double|long double", 1},
    {"jn", "", 1, "double|int|double", 1},
    {"jnf", "", 1, "float|int|float", 1},
    {"jnl", "", 1, "long double|int|long double", 1},
    {"labs", "<stdlib.h>", 1, "long int|long int", 0},
    {"lceil", "", 0, "long int|double", 2},
    {"lceilf", "", 0, "long int|float", 2},
    {"lceill", "", 0, "long int|long double", 2},
    {"ldexp", "<math.h>", 1, "double|double|int", 0},
    {"ldexpf", "<math.h>", 1, "float|float|int", 0},
    {"ldexpl", "<math.h>", 1, "long double|long double|int", 0},
    {"lfloor", "", 0, "long int|double", 2},
    {"lfloorf", "", 0, "long int|float", 2},
    {"lfloorl", "", 0, "long int|long double", 2},
    {"lgamma", "<math.h>", 1, "double|double", 0},
    {"lgamma_r", "", 1, "double|double|int *", 1},
    {"lgammaf", "<math.h>", 1, "float|float", 0},
    {"lgammaf_r", "", 1, "float|float|int *", 1},
    {"lgammal", "<math.h>", 1, "long double|long double", 0},
    {"lgammal_r", "", 1, "long double|long double|int *", 1},
    {"llabs", "<stdlib.h>", 1, "long long int|long long int", 0},
    {"llceil", "", 0, "long long int|double", 2},
    {"llceilf", "", 0, "long long int|float", 2},
    {"llceill", "", 0, "long long int|long double", 2},
    {"llfloor", "", 0, "long long int|double", 2},
    {"llfloorf", "", 0, "long long int|float", 2},
    {"llfloorl", "", 0, "long long int|long double", 2},
    {"log", "<math.h>", 1, "double|double", 0},
    {"log10", "<math.h>", 1, "double|double", 0},
    {"log10f", "<math.h>", 1, "float|float", 0},
    {"log10l", "<math.h>", 1, "long double|long double", 0},
    {"log1p", "<math.h>", 1, "double|double", 0},
    {"log1pf", "<math.h>", 1, "float|float", 0},
    {"log1pl", "<math.h>", 1, "long double|long double", 0},
    {"log2", "<math.h>", 1, "double|double", 0},
    {"log2f", "<math.h>", 1, "float|float", 0},
    {"log2l", "<math.h>", 1, "long double|long double", 0},
    {"logb", "<math.h>", 1, "double|double", 0},
    {"logbf", "<math.h>", 1, "float|float", 0},
    {"logbl", "<math.h>", 1, "long double|long double", 0},
    {"logf", "<math.h>", 1, "float|float", 0},
    {"logl", "<math.h>", 1, "long double|long double", 0},
    {"longjmp", "", 0, "void|void *|int", 2},
    {"malloc", "<stdlib.h>", 1, "void *|long unsigned int", 0},
    {"memchr", "<string.h>", 1, "void *|const void *|int|long unsigned int", 0},
    {"memcmp", "<string.h>", 0, "int|const void *|const void *|long unsigned int", 0},
    {"memcmp_eq", "", 0, "int|const void *|const void *|long unsigned int", 2},
    {"memcpy", "<string.h>", 1, "void *|void *|const void *|long unsigned int", 0},
    {"memmove", "<string.h>", 1, "void *|void *|const void *|long unsigned int", 0},
    {"mempcpy", "", 1, "void *|void *|const void *|long unsigned int", 1},
    {"memset", "<string.h>", 1, "void *|void *|int|long unsigned int", 0},
    {"modf", "<math.h>", 1, "double|double|double *", 0},
    {"modff", "<math.h>", 1, "float|float|float *", 0},
    {"modfl", "<math.h>", 1, "long double|long double|long double *", 0},
    {"nan", "<math.h>", 1, "double|const char *", 0},
    {"nanf", "<math.h>", 1, "float|const char *", 0},
    {"nanl", "<math.h>", 1, "long double|const char *", 0},
    {"nanq", "", 0, "__float128|const char *", 3},
    {"nans", "", 0, "double|const char *", 2},
    {"nansf", "", 0, "float|const char *", 2},
    {"nansl", "", 0, "long double|const char *", 2},
    {"nansq", "", 0, "__float128|const char *", 3},
    {"nearbyint", "<math.h>", 1, "double|double", 0},
    {"nearbyintf", "<math.h>", 1, "float|float", 0},
    {"nearbyintl", "<math.h>", 1, "long double|long double", 0},
    {"next_arg", "", 0, "void *|", 2},
    {"nextafter", "<math.h>", 1, "double|double|double", 0},
    {"nextafterf", "<math.h>", 1, "float|float|float", 0},
    {"nextafterl", "<math.h>", 1, "long double|long double|long double", 0},
    {"nexttoward", "<math.h>", 1, "double|double|long double", 0},
    {"nexttowardf", "<math.h>", 1, "float|float|long double", 0},
    {"nexttowardl", "<math.h>", 1, "long double|long double|long double", 0},
    {"nonlocal_goto", "", 0, "void|void *|void *", 2},
    {"object_size", "", 0, "long unsigned int|const void *|int", 2},
    {"parity", "", 0, "int|unsigned int", 2},
    {"parityimax", "", 0, "int|long unsigned int", 2},
    {"parityl", "", 0, "int|long unsigned int", 2},
    {"parityll", "", 0, "int|long long unsigned int", 2},
    {"popcount", "", 0, "int|unsigned int", 2},
    {"popcountimax", "", 0, "int|long unsigned int", 2},
    {"popcountl", "", 0, "int|long unsigned int", 2},
    {"popcountll", "", 0, "int|long long unsigned int", 2},
    {"posix_memalign", "", 0, "int|void **|long unsigned int|long unsigned int", 1},
    {"pow", "<math.h>", 1, "double|double|double", 0},
    {"pow10", "", 1, "double|double", 1},
    {"pow10f", "", 1, "float|float", 1},
    {"pow10l", "", 1, "long double|long double", 1},
    {"powf", "<math.h>", 1, "float|float|float", 0},
    {"powi", "", 0, "double|double|int", 2},
    {"powif", "", 0, "float|float|int", 2},
    {"powil", "", 0, "long double|long double|int", 2},
    {"powl", "<math.h>", 1, "long double|long double|long double", 0},
    {"prefetch", "", 0, "void|const void *|...", 2},
    {"printf", "<stdio.h>", 1, "int|const char *|...", 0},
    {"printf_unlocked", "", 1, "int|const char *|...", 1},
    {"putc", "<stdio.h>", 0, "int|int|void *", 0},
    {"putc_unlocked", "", 0, "int|int|void *", 1},
    {"putchar", "<stdio.h>", 0, "int|int", 0},
    {"putchar_unlocked", "", 0, "int|int", 1},
    {"puts", "<stdio.h>", 0, "int|const char *", 0},
    {"puts_unlocked", "", 0, "int|const char *", 1},
    {"realloc", "<stdlib.h>", 1, "void *|void *|long unsigned int", 0},
    {"remainder", "<math.h>", 1, "double|double|double", 0},
    {"remainderf", "<math.h>", 1, "float|float|float", 0},
    {"remainderl", "<math.h>", 1, "long double|long double|long double", 0},
    {"remquo", "<math.h>", 1, "double|double|double|int *", 0},
    {"remquof", "<math.h>", 1, "float|float|float|int *", 0},
    {"remquol", "<math.h>", 1, "long double|long double|long double|int *", 0},
    {"return", "", 0, "void|void *", 2},
    {"return_address", "", 0, "void *|unsigned int", 2},
    {"rindex", "", 1, "char *|const char *|int", 1},
    {"rint", "<math.h>", 1, "double|double", 0},
    {"rintf", "<math.h>", 1, "float|float", 0},
    {"rintl", "<math.h>", 1, "long double|long double", 0},
    {"round", "<math.h>", 1, "double|double", 0},
    {"roundeven", "", 1, "double|double", 1},
    {"roundevenf", "", 1, "float|float", 1},
    {"roundevenl", "", 1, "long double|long double", 1},
    {"roundf", "<math.h>", 1, "float|float", 0},
    {"roundl", "<math.h>", 1, "long double|long double", 0},
    {"saveregs", "", 0, "void *|", 2},
    {"scalb", "", 1, "double|double|double", 1},
    {"scalbf", "", 1, "float|float|float", 1},
    {"scalbl", "", 1, "long double|long double|long double", 1},
    {"scalbln", "<math.h>", 1, "double|double|long int", 0},
    {"scalblnf", "<math.h>", 1, "float|float|long int", 0},
    {"scalblnl", "<math.h>", 1, "long double|long double|long int", 0},
    {"scalbn", "<math.h>", 1, "double|double|int", 0},
    {"scalbnf", "<math.h>", 1, "float|float|int", 0},
    {"scalbnl", "<math.h>", 1, "long double|long double|int", 0},
    {"scanf", "<stdio.h>", 1, "int|const char *|...", 0},
    {"set_thread_pointer", "", 0, "void|void *", 2},
    {"setjmp", "", 0, "int|void *", 2},
    {"setjmp_receiver", "", 0, "void|void *", 2},
    {"setjmp_setup", "", 0, "void|void *|void *", 2},
    {"signbitf", "", 1, "int|float", 1},
    {"signbitl", "", 0, "int|long double", 1},
    {"significand", "", 1, "double|double", 1},
    {"significandf", "", 1, "float|float", 1},
    {"significandl", "", 1, "long double|long double", 1},
    {"sin", "<math.h>", 1, "double|double", 0},
    {"sincos", "", 1, "void|double|double *|double *", 1},
    {"sincosf", "", 1, "void|float|float *|float *", 1},
    {"sincosl", "", 1, "void|long double|long double *|long double *", 1},
    {"sinf", "<math.h>", 1, "float|float", 0},
    {"sinh", "<math.h>", 1, "double|double", 0},
    {"sinhf", "<math.h>", 1, "float|float", 0},
    {"sinhl", "<math.h>", 1, "long double|long double", 0},
    {"sinl", "<math.h>", 1, "long double|long double", 0},
    {"snprintf", "<stdio.h>", 1, "int|char *|long unsigned int|const char *|...", 0},
    {"speculation_safe_value_8", "", 0, "long unsigned int|long unsigned int|...", 2},
    {"speculation_safe_value_ptr", "", 0, "void *|void *|...", 2},
    {"sprintf", "<stdio.h>", 1, "int|char *|const char *|...", 0},
    {"sqrt", "<math.h>", 1, "double|double", 0},
    {"sqrtf", "<math.h>", 1, "float|float", 0},
    {"sqrtl", "<math.h>", 1, "long double|long double", 0},
    {"sscanf", "<stdio.h>", 1, "int|const char *|const char *|...", 0},
    {"stack_restore", "", 0, "void|void *", 2},
    {"stack_save", "", 0, "void *|", 2},
    {"stpcpy", "", 1, "char *|char *|const char *", 1},
    {"stpncpy", "", 1, "char *|char *|const char *|long unsigned int", 1},
    {"strcasecmp", "", 0, "int|const char *|const char *", 1},
    {"strcat", "<string.h>", 1, "char *|char *|const char *", 0},
    {"strchr", "<string.h>", 1, "char *|const char *|int", 0},
    {"strcmp", "<string.h>", 0, "int|const char *|const char *", 0},
    {"strcmp_eq", "", 0, "int|const void *|const void *|long unsigned int", 2},
    {"strcpy", "<string.h>", 1, "char *|char *|const char *", 0},
    {"strcspn", "<string.h>", 1, "long unsigned int|const char *|const char *", 0},
    {"strdup", "", 1, "char *|const char *", 1},
    {"strfmon", "", 1, "long int|char *|long unsigned int|const char *|...", 1},
    {"strftime", "<time.h>", 1, "long unsigned int|char *|long unsigned int|const char *|const void *", 0},
    {"strlen", "<string.h>", 1, "long unsigned int|const char *", 0},
    {"strncasecmp", "", 0, "int|const char *|const char *|long unsigned int", 1},
    {"strncat", "<string.h>", 1, "char *|char *|const char *|long unsigned int", 0},
    {"strncmp", "<string.h>", 0, "int|const char *|const char *|long unsigned int", 0},
    {"strncmp_eq", "", 0, "int|const void *|const void *|long unsigned int", 2},
    {"strncpy", "<string.h>", 1, "char *|char *|const char *|long unsigned int", 0},
    {"strndup", "", 1, "char *|const char *|long unsigned int", 1},
    {"strnlen", "", 1, "long unsigned int|const char *|long unsigned int", 1},
    {"strpbrk", "<string.h>", 1, "char *|const char *|const char *", 0},
    {"strrchr", "<string.h>", 1, "char *|const char *|int", 0},
    {"strspn", "<string.h>", 1, "long unsigned int|const char *|const char *", 0},
    {"strstr", "<string.h>", 1, "char *|const char *|const char *", 0},
    {"tan", "<math.h>", 1, "double|double", 0},
    {"tanf", "<math.h>", 1, "float|float", 0},
    {"tanh", "<math.h>", 1, "double|double", 0},
    {"tanhf", "<math.h>", 1, "float|float", 0},
    {"tanhl", "<math.h>", 1, "long double|long double", 0},
    {"tanl", "<math.h>", 1, "long double|long double", 0},
    {"tgamma", "<math.h>", 1, "double|double", 0},
    {"tgammaf", "<math.h>", 1, "float|float", 0},
    {"tgammal", "<math.h>", 1, "long double|long double", 0},
    {"thread_pointer", "", 0, "void *|", 2},
    {"toascii", "", 0, "int|int", 1},
    {"tolower", "<ctype.h>", 0, "int|int", 0},
    {"toupper", "<ctype.h>", 0, "int|int", 0},
    {"trap", "", 0, "void|", 2},
    {"trunc", "<math.h>", 1, "double|double", 0},
    {"truncf", "<math.h>", 1, "float|float", 0},
    {"truncl", "<math.h>", 1, "long double|long double", 0},
    {"unreachable", "", 0, "void|", 2},
    {"unwind_init", "", 0, "void|", 2},
    {"unwind_resume", "", 0, "void|void *", 2},
    {"update_setjmp_buf", "", 0, "void|void *", 2},
    {"va_arg_pack", "", 0, "int|", 2},
    {"va_arg_pack_len", "", 0, "int|", 2},
    {"vfprintf", "<stdio.h>", 0, "int|void *|const char *|__va_list_tag *", 0},
    {"vfscanf", "<stdio.h>", 0, "int|void *|const char *|__va_list_tag *", 0},
    {"vprintf", "<stdio.h>", 0, "int|const char *|__va_list_tag *", 0},
    {"vscanf", "<stdio.h>", 0, "int|const char *|__va_list_tag *", 0},
    {"vsnprintf", "<stdio.h>", 0, "int|char *|long unsigned int|const char *|__va_list_tag *", 0},
    {"vsprintf", "<stdio.h>", 0, "int|char *|const char *|__va_list_tag *", 0},
    {"vsscanf", "<stdio.h>", 0, "int|const char *|const char *|__va_list_tag *", 0},
    {"y0", "", 1, "double|double", 1},
    {"y0f", "", 1, "float|float", 1},
    {"y0l", "", 1, "long double|long double", 1},
    {"y1", "", 1, "double|double", 1},
    {"y1f", "", 1, "float|float", 1},
    {"y1l", "", 1, "long double|long double", 1},
    {"yn", "", 1, "double|int|double", 1},
    {"ynf", "", 1, "float|int|float", 1},
    {"ynl", "", 1, "long double|int|long double", 1},
};
