#!/bin/sh
# probe-host.sh CC OUT.c
# Bakes the host compiler's C99 view of the world into a C source file:
# system include directories, predefined macros, and the answers to
# __has_attribute / __has_builtin for every name the host headers ask about.
set -eu
HOSTCC=${1:-cc}
OUT=${2:-build/gen/host_config.c}
TMP=${TMPDIR:-/tmp}/cereal-probe.$$
mkdir -p "$TMP" "$(dirname "$OUT")"
trap 'rm -rf "$TMP"' EXIT INT TERM

cesc() { sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

# 1. include search path
$HOSTCC -std=c99 -E -v -x c /dev/null 2>&1 >/dev/null |
    sed -n '/#include <...> search starts here:/,/End of search list./p' |
    sed -e '1d' -e '$d' -e 's/^ *//' >"$TMP/dirs"

# 2. predefined macros (the standard ones are provided by cereal itself)
$HOSTCC -std=c99 -dM -E -x c /dev/null |
    grep -v -E '^#define (__STDC__|__STDC_VERSION__|__STDC_HOSTED__) ' |
    LC_ALL=C sort >"$TMP/predefs"

# 3. __has_attribute / __has_builtin names used by the host headers
: >"$TMP/attr_names"
: >"$TMP/builtin_names"
while read -r d; do
    [ -d "$d" ] || continue
    grep -rhoE '__(glibc_)?has_(c_)?attribute *\( *[A-Za-z_][A-Za-z0-9_]*' "$d" 2>/dev/null |
        sed -E 's/.*\( *//' >>"$TMP/attr_names" || true
    grep -rhoE '__(glibc_)?has_builtin *\( *[A-Za-z_][A-Za-z0-9_]*' "$d" 2>/dev/null |
        sed -E 's/.*\( *//' >>"$TMP/builtin_names" || true
done <"$TMP/dirs"
for n in noreturn nonnull pure const malloc format deprecated unused used \
    always_inline noinline warn_unused_result visibility alias weak \
    fallthrough nodiscard maybe_unused packed aligned cold hot; do
    echo "$n" >>"$TMP/attr_names"
done
LC_ALL=C sort -u "$TMP/attr_names" -o "$TMP/attr_names"
LC_ALL=C sort -u "$TMP/builtin_names" -o "$TMP/builtin_names"

probe() { # probe KIND FILE -> names the host says yes to
    : >"$TMP/probe.c"
    while read -r n; do
        printf '#if %s(%s)\nYES_%s\n#endif\n' "$1" "$n" "$n" >>"$TMP/probe.c"
    done <"$2"
    $HOSTCC -std=c99 -E -P "$TMP/probe.c" 2>/dev/null |
        sed -n 's/^YES_//p' || true
}
probe __has_attribute "$TMP/attr_names" >"$TMP/attrs"
probe __has_builtin "$TMP/builtin_names" >"$TMP/builtins"

{
    echo "/* Generated by tools/probe-host.sh from '$HOSTCC'. Do not edit. */"
    echo "#include <stddef.h>"
    echo "const char *const host_cc_name = \"$(printf '%s' "$HOSTCC" | cesc)\";"
    echo "const char *const host_include_dirs[] = {"
    cesc <"$TMP/dirs" | sed 's/.*/    "&",/'
    echo "    NULL};"
    echo "const char *const host_attrs[] = {"
    sed 's/.*/    "&",/' "$TMP/attrs"
    echo "    NULL};"
    echo "const char *const host_builtins[] = {"
    sed 's/.*/    "&",/' "$TMP/builtins"
    echo "    NULL};"
    echo "const char host_predefs[] ="
    cesc <"$TMP/predefs" | sed 's/.*/    "&\\n"/'
    echo "    \"\";"
} >"$OUT"
