#!/usr/bin/env python3
"""gen_ucn99.py ucnid.tab > src/ucn99.h
The characters ISO C99 Annex D allows in an identifier (gcc's [C99] and
[C99DIG] sections of libcpp/ucnid.tab; the digits may not start one)."""
import sys, re

secs = {}
cur = None
for line in open(sys.argv[1]):
    line = line.split(";")[0].strip()
    if not line or line.startswith("#"):
        continue
    m = re.match(r"\[(\w+)\]$", line)
    if m:
        cur = m.group(1)
        secs[cur] = []
        continue
    if cur is None:
        continue
    for tok in line.split():
        lo, _, hi = tok.partition("-")
        secs[cur].append((int(lo, 16), int(hi or lo, 16)))
rows = sorted([(a, b, 0) for a, b in secs["C99"]] +
              [(a, b, 1) for a, b in secs["C99DIG"]])
print("/* Generated by bench/tools/gen_ucn99.py from gcc 13's libcpp/ucnid.tab:")
print(" * the C99 Annex D identifier characters {lo, hi, may not start}. */")
print("static const struct { uint16_t lo, hi, nostart; } ucn99[] = {")
for a, b, f in rows:
    print("    {0x%04x, 0x%04x, %d}," % (a, b, f))
print("};")
