#!/usr/bin/env python3
"""Generate src/gcc_pragma_opts.h: how gcc-13 classifies the option string of
`#pragma GCC diagnostic KIND "-Xyz"` (probed from gcc itself).

  pragma_nonc[]    -W options that exist only for other languages, with the
                   language list gcc prints ("C++/ObjC++", "Fortran", ...)
  pragma_notwarn[] options that exist but do not control warnings
                   (-fstrict-aliasing, -Werror, -O2, ...); a trailing '='
                   marks an option that needs a value

Anything else under -W is looked up in gcc_wopts.h (known: silent; unknown:
"unknown option after ... kind").  Usage: gen_pragma_opts.py > src/gcc_pragma_opts.h
(needs gcc-13).
"""
import re, subprocess, sys, tempfile, os

def probe(strings):
    d = tempfile.mkdtemp()
    p = os.path.join(d, 'p.c')
    open(p, 'w').write('\n'.join('#pragma GCC diagnostic ignored "%s"' % s for s in strings) + '\nint i;\n')
    out = subprocess.run(['gcc-13', '-fsyntax-only', p], capture_output=True, text=True).stderr
    res = {}
    for l in out.split('\n'):
        m = re.match(r'.*p\.c:(\d+):\d+: warning: (.*) \[-Wpragmas\]', l)
        if m:
            res[int(m.group(1)) - 1] = m.group(2)
    return [res.get(i) for i in range(len(strings))]

src = os.path.join(os.path.dirname(__file__), '..', '..', 'src', 'gcc_wopts.h')
wnames = [n for n in re.findall(r'"([^"]*)"', open(src).read()) if n and not n.endswith('-')]
r = probe(['-W' + n + ('1' if n.endswith('=') else '') for n in wnames])
nonc, notw = [], []
for n, m in zip(wnames, r):
    if m is None:
        continue
    q = re.match(r"option ‘[^’]*’ is valid for (.*) but not for C$", m)
    if q:
        nonc.append((n, q.group(1)))
    elif 'not an option' in m:
        notw.append('W' + n)

allopts = set()
for cat in ('common', 'optimizers', 'target', 'c', 'warnings'):
    o = subprocess.run(['gcc-13', '-Q', '--help=' + cat], capture_output=True, text=True).stdout
    for l in o.split('\n'):
        if l.startswith('  -') and not l.startswith('  --'):
            a = l.split()[0]
            allopts.add(re.split(r'[=\[<]', a)[0])
extra = ['-O2', '-O', '-Os', '-Ofast', '-Og', '-O0', '-pedantic', '-w', '-g', '-ggdb', '-pipe', '-pedantic-errors', '-ansi']
cand = sorted(o for o in allopts if not o.startswith('-W') and o.startswith('-')) + extra
r1 = probe(cand)
need_val = [c for c, m in zip(cand, r1) if m is not None and 'unknown' in m]
r2 = probe([c + '=1' for c in need_val])
for c, m in zip(cand, r1):
    if m is not None and 'not an option' in m:
        notw.append(c[1:])
for c, m in zip(need_val, r2):
    if m is not None and 'not an option' in m:
        notw.append(c[1:] + '=')
notw = sorted(set(notw))
print('/* Generated by bench/tools/gen_pragma_opts.py from gcc-13: the option strings\n'
      ' * of #pragma GCC diagnostic that gcc classifies other than "a warning of C". */')
print('static const struct { const char *name, *langs; } pragma_nonc[] = {')
for n, l in sorted(nonc):
    print('    {"%s", "%s"},' % (n, l))
print('};')
print('static const char *const pragma_notwarn[] = {')
for n in notw:
    print('    "%s",' % n)
print('};')
