#!/usr/bin/env python3
"""Generate src/gcc_optimize_opts.h: the option strings gcc-13 accepts in
`#pragma GCC optimize ("...")` and __attribute__((optimize("..."))) (the options
flagged Optimization), probed from gcc itself.  'n=' marks an option that may take a value, 'n==' one that needs it.  Everything else (-fno-lto, -Wall, -march=..., -g, ...) is
"bad option '...' to pragma 'optimize'".

Usage: gen_optimize_opts.py > src/gcc_optimize_opts.h   (needs gcc-13)
"""
import re, subprocess, tempfile, os

def sh(*a):
    return subprocess.run(list(a), capture_output=True, text=True)

names = set()
for cat in ('common', 'optimizers', 'target', 'c', 'warnings', 'params'):
    for l in sh('gcc-13', '-Q', '--help=' + cat).stdout.split('\n'):
        if l.startswith('  -f') or l.startswith('  --param'):
            a = l.split()[0]
            val = bool(re.search(r'[=<\[]', a))
            base = re.split(r'[=<\[]', a)[0]
            names.add(base + ('=' if val else ''))
cand = []
for n in sorted(names):
    cand.append(n)
    if n.startswith('-f') and not n.startswith('-fno-'):
        cand.append('-fno-' + n[2:])

def probe(strings):
    d = tempfile.mkdtemp()
    p = os.path.join(d, 'p.c')
    src = []
    for s in strings:
        src.append('#pragma GCC optimize ("%s")' % s)
    open(p, 'w').write('\n'.join(src) + '\nint i;\n')
    out = sh('gcc-13', '-fsyntax-only', p).stderr
    bad = set()
    for l in out.split('\n'):
        m = re.match(r'.*p\.c:(\d+):\d+: (warning|error)', l)
        if m:
            bad.add(int(m.group(1)) - 1)
    return [i not in bad for i in range(len(strings))]

bare = [c.rstrip('=') for c in cand]
okb = set(b for b, g in zip(bare, probe(bare)) if g)
vals = [c for c in cand if c.endswith('=')]
okv = set()
for v in ('1', 'cheap', 'default', 'yes', 'all', 'dynamic', 'none'):
    for c, g in zip(vals, probe([c + v for c in vals])):
        if g:
            okv.add(c)
ok = set()
for c in cand:
    b = c.rstrip('=')
    if c.endswith('='):
        if b in okb and c in okv:
            ok.add(c)             # bare or with a value
        elif c in okv:
            ok.add(c + '=')       # needs a value
        elif b in okb:
            ok.add(b)
    elif b in okb:
        ok.add(b)
ok = sorted(ok)
print('/* Generated by bench/tools/gen_optimize_opts.py from gcc-13: the options\n'
      ' * #pragma GCC optimize accepts (a trailing \'=\' takes a value). */')
print('static const char *const optimize_ok[] = {')
for o in ok:
    print('    "%s",' % o)
print('};')
