#!/usr/bin/env python3
"""gen_nfc.py libcpp/ucnid.h > src/ucnorm.h
The normalisation data libcpp uses for -Wnormalized (charset.cc
ucn_valid_in_identifier): per code point the combining class and how the
character affects the NFC/NFKC state, and the (c, previous starter) pairs
check_nfc reports as not in NFC.  Kinds: 0 none, 1 NKC (no change), 2 NFC,
3 CID, 4 CTX (look at the previous starter)."""
import re
import sys

src = open(sys.argv[1]).read()
lic = src[:src.index("*/") + 2]

rows = []
prev_end = -1
for m in re.finditer(r"^\{([^}]*),\s*(\d+),\s*0x([0-9a-f]+) \},$", src, re.M):
    flags, comb, end = m.group(1), int(m.group(2)), int(m.group(3), 16)
    f = set(re.findall(r"\b(CID|NFC|NKC|CTX)\b", flags))
    kind = 4 if "CTX" in f else 1 if "NKC" in f else 2 if "NFC" in f \
        else 3 if "CID" in f else 0
    lo = prev_end + 1
    prev_end = end
    if rows and rows[-1][1] + 1 == lo and rows[-1][2:] == [comb, kind]:
        rows[-1][1] = end
    else:
        rows.append([lo, end, comb, kind])
# characters in no range of the table are never identifier characters

pairs = []
body = src[src.index("check_nfc (cpp_reader"):]
outer = None
labels = []
for line in body.splitlines():
    m = re.match(r"    case 0x([0-9a-f]+):", line)
    if m:
        outer = int(m.group(1), 16)
        labels = []
        continue
    m = re.match(r"\tcase 0x([0-9a-f]+):", line)
    if m:
        labels.append(int(m.group(1), 16))
    elif "return false" in line:
        pairs += [(outer, p) for p in labels]
        labels = []
    elif "return true" in line:
        labels = []
pairs.sort()

print(lic.replace("/* Unicode characters", "/* Generated by bench/tools/gen_nfc.py from gcc 13's libcpp/ucnid.h;\n   Unicode characters", 1))
print()
print("/* {lo, hi, combining class, kind} */")
print("static const struct { uint32_t lo, hi; uint8_t comb, kind; } ucnorm[] = {")
for i in range(0, len(rows), 3):
    print("    " + " ".join("{0x%x, 0x%x, %d, %d}," % tuple(r)
                            for r in rows[i:i + 3]))
print("};")
print()
print("/* (c, previous starter) pairs that are not in NFC, sorted */")
print("static const struct { uint32_t c, p; } nfc_bad[] = {")
for i in range(0, len(pairs), 4):
    print("    " + " ".join("{0x%x, 0x%x}," % t for t in pairs[i:i + 4]))
print("};")
