#!/usr/bin/env python3
"""Probe gcc-13: which __builtin_NAME calls are const/pure (an unused result
warns "statement with no effect")?  Writes src/c/cbuiltin_pure.h.
Run from the repo root.  Arguments are non-constant (a constant argument
lets gcc fold the call, which hides the warning)."""
import re, subprocess, sys

src = open('src/c/cbuiltin_tab.h').read()
ents = re.findall(r'\{"(\w+)", "[^"]*", \d, "([^"]*)", (\d)\}', src)
lines, names = [], []
for n, sig, g in ents:
    if '?' in sig:
        continue
    args = [p for p in sig.split('|')[1:] if p]
    if any('...' in a for a in args):
        continue
    call = ', '.join(('(%s)gp' % a) if '*' in a else ('(%s)gd' % a) if
                     ('double' in a or 'float' in a) else ('(%s)gi' % a)
                     for a in args)
    names.append(n)
    lines.append('void f%d(void){ __builtin_%s(%s); }' % (len(names), n, call))
open('/tmp/pure_probe.c', 'w').write(
    'char gp[64]; int gi; double gd;\n' + '\n'.join(lines) + '\n')
r = subprocess.run(['gcc-13', '-fsyntax-only', '-Wunused-value',
                    '/tmp/pure_probe.c'], capture_output=True, text=True)
hit = set()
for m in re.finditer(r'pure_probe\.c:(\d+):\d+: warning: '
                     r'(statement with no effect|value computed is not used)',
                     r.stderr):
    hit.add(names[int(m.group(1)) - 2])
print(len(names), len(hit), file=sys.stderr)
out = ['/* gcc 13 builtins whose call has no side effects (const or pure): an '
       'unused result',
       ' * is "statement with no effect".  Generated by '
       'bench/tools/gen_pure_builtins.py. */',
       'static const char *const cbuiltin_pure[] = {']
out += ['    "%s",' % n for n in sorted(hit)]
out.append('};')
open('src/c/cbuiltin_pure.h', 'w').write('\n'.join(out) + '\n')
