#!/usr/bin/env python3
"""gen_ucnx.py ucnid.tab > src/ucnx.h
The characters gcc 13 accepts in an identifier without -pedantic: the union of
the C99, C++ and C11 sets (libcpp ucn_valid_in_identifier), with whether one
may start an identifier ({lo, hi, class}: 1 yes, 2 only after the first)."""
import re
import sys

secs = {}
cur = None
for line in open(sys.argv[1]):
    line = line.split(";")[0].strip()
    if not line or line.startswith("#"):
        continue
    m = re.match(r"\[(\w+)\]$", line)
    if m:
        cur = m.group(1)
        secs[cur] = []
        continue
    if cur is None:
        continue
    for tok in line.split():
        lo, _, hi = tok.partition("-")
        secs[cur].append((int(lo, 16), int(hi or lo, 16)))


def cover(name):
    s = set()
    for a, b in secs.get(name, []):
        s.update(range(a, b + 1))
    return s


c99, n99 = cover("C99") | cover("C99DIG"), cover("C99DIG")
cxx = cover("CXX")
c11, n11 = cover("C11") | cover("C11NOSTART"), cover("C11NOSTART")
rows = []
for cp in sorted(c99 | cxx | c11):
    ok = (cp in c99 and cp not in n99) or cp in cxx or \
         (cp in c11 and cp not in n11)
    k = 1 if ok else 2
    if rows and rows[-1][1] + 1 == cp and rows[-1][2] == k:
        rows[-1][1] = cp
    else:
        rows.append([cp, cp, k])
print("/* Generated by bench/tools/gen_ucnx.py from gcc 13's libcpp/ucnid.tab:")
print(" * identifier characters without -pedantic {lo, hi, class}. */")
print("static const struct { uint32_t lo, hi; uint8_t cls; } ucnx[] = {")
for i in range(0, len(rows), 3):
    print("    " + " ".join("{0x%x, 0x%x, %d}," % tuple(r)
                            for r in rows[i:i + 3]))
print("};")
